### ISSUE TITLE
A way to travel to The Hallow

### ISSUE THREAD

**Issue by cplir-c** [fabric-community/spooky-time#120]
I propose:

for a portal you need to:
- kill a chicken or snow golem
- in an area
- with all (most? many? of) the features of spookytime available in the overworld in the area
- with the lights out
- with a tiny pumpkin
- When the chicken dies there's a "Squash!" sound effect
- A witched pumpkin is placed where the chicken died
- and the surroundings fade to the spooky dimension
- if there aren't enough spooky things in the area, the chicken dies with a "Sqawk!" or something instead

**Comment by Shnupbups** [comment]
This seems a bit convoluted

**Comment by cplir-c** [comment]
How about dying to a witch after being tricked instead of treated does the following:
- puts a witched pumpkin where you died
- sends you to the spooky dimension, optionally leaving your items behind

**Comment by Shnupbups** [comment]
That's heavily chance-based, which I don't like the idea of.

**Comment by ElectricProgramer** [comment]
Or you could build a ring of Jack-o-Lanterns and drop something in the center to create a spooky portal

**Comment by cplir-c** [comment]
Some requirements for the mechanic?

**Comment by cplir-c** [comment]
before we get into specifics
it seems my ideas were off course

**Comment by cplir-c** [comment]
- possible nether gate
- easy to get to the Spook after going there once
- preferably spooky?
- sure to work
    - not finnicky
        - not requiring a large structure
        - not chance based
    - repeatable

**Comment by Shnupbups** [comment]
1. gated behind the nether (as in, you need to get something from the nether to be able to get into the spooklands)
2. not too convoluted, we don't want it to have too complex of a set up
3. avoid being chance-based

however, we *can* make it based on something like phases of the moon or something you'd have to wait for *provided* that there be a non-time gated way to travel there after doing the initial travel

**Comment by ElectricProgramer** [comment]
You can only activate the portal at night during a full moon maybe, but afterwards it's always available.

**Comment by cplir-c** [comment]
falling into lava in the nether while wearing a pumpkin from a height that would otherwise kill you?

**Comment by cplir-c** [comment]
eating magma cream while trick or treating?

**Comment by ElectricProgramer** [comment]
During a Full Moon, drop a piece of sugar, a blaze rod, and some more items on a Lit Jack-O-Lantern. The Jack-O-Lantern will be converted into some kind of portal pumpkin which, while stood on, will transport you to the dimension.

**Comment by Draylar** [comment]
Sleep during a full moon while wearing a wither skeleton skull~

**Comment by cplir-c** [comment]
> əนѻʇƨρәɻ_ҋا_ʇɒƆ: 
> intercepted progress: what if nether portals bring you to the spook the first time you go in one :)
>  
> GiantNuker : 
> me likey
> and randomly afterwards
> bonus points if you dont put it in the mod description

**Comment by i509VCB** [comment]
Require it to be night time and a witch within a certain distance to open an altar. The altar requires jack o lanterns, a few lanterns, a few bits of water (these will be witched) and pumpkin in the center. Some block from the nether as a sort of base. 

After the altar is built drop the anvil onto the pumpkin in the center and the gate opening sequence will begin.

Of course the sequence has to involve some amount of lightning.

**Comment by valoeghese** [comment]
Nah mate make the altars naturally generated structures in the overworld :P

**Comment by valoeghese** [comment]
But you have to activate them

**Comment by LemmaEOF** [comment]
#164

**Comment by cplir-c** [comment]
Implemented and working
