### ISSUE TITLE
Tombstone

### ISSUE THREAD

**Issue by vronc** [fabric-community/spooky-time#138]
Hi!

I've never modded Minecraft before but I see this repo as a great opportunity to start! I've managed to get everything working and have set up a mesh for a tombstone! 
It would only be a decorative piece that I guess could be crafted from some sort of stone blocks.
Would that be cool?

**Comment by vini2003** [comment]
Sure!

Put it up as a PR and we can help you throughout the way :)

**Comment by vronc** [comment]
Thank you! :dancer:
