### ISSUE TITLE
Rename to 'Atrocity'

### ISSUE THREAD

**Issue by vini2003** [fabric-community/spooky-time#146]
Currently, Spooky Time just doesn't sound like a serious mod, which is the direction we're heading at. It sounds like a mod jam mod made for fun for Halloween and not something people should use seriously.

In other words, I believe we should rename it - in my case, using @AK9Official's suggestion:

# Atrocity

Where the dimension would be called:

# The Atrocity

Seems good to me.

**Comment by Shnupbups** [comment]
no
