### ISSUE TITLE
JIJ Trinkets

### ISSUE THREAD

**Issue by Draylar** [fabric-community/spooky-time#169]
Trinkets is a required dependency, but isn't included in the main project jar. The main issue with standard JiJing it is that Emi gets no downloads on CF. We can solve this by pointing our Trinket dependency at the CurseForge project page (and then including it, which increments the download count for each unique download from a player).

**Comment by LemmaEOF** [comment]
I think marking Trinkets as "embedded" on CF might also increment the Trinkets dl count? I have no idea

**Comment by Shrimpstress** [comment]
Considering that my mod Wrench Anything has ~200 and Wrenchable (even though it's a library which should be JiJed) has ~100 it would surprise me too much.

Does make me wonder why there's a difference in download numbers if so though.
