### ISSUE TITLE
server crash when firing shotgun

### ISSUE THREAD

**Issue by spyguy26** [fabric-community/spooky-time#183]
when firing the shotgun on a dedicated server the server immediately crashes

crash log is here: https://gist.github.com/spyguy26/ce06b6a4e12fa8eb393db914252a9f1d

fabric loader version: 0.6.4+build.169
fabric api version: fabric-api-0.4.1+build.245-1.14
The Hallow version: TheHallow-1.1.0-beta+1.14.4
Trinkets version: trinkets-2.1.1

**Comment by Shrimpstress** [comment]
The cause is that `ShotgunProjectileEntity` is calling a client-side version of getEyeHeight. Can easily be fixed by switching to the version that requests both a pose and EntityDimensions. We'll have this fixed for the next build.

**Comment by Shrimpstress** [comment]
The shotgun is no longer supported, and will be removed in the next build.
