### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by Yoghurt4C** [fabric-community/spooky-time#198]
this is stupid fabric is already good this is bad fuck you delete this shit ur dim sucks use fabric mother fuckers hallow sucks fabric is perfect awesome good for mod needs no hallow is hacks hacks HACKS hallowe stupid delete or remove

**Comment by shedaniel** [comment]
good job i approve

**Comment by ImAK9** [comment]
no no go boom boom
