### ISSUE TITLE
Spooky Treasure Chest

### ISSUE THREAD

**Issue by Draylar** [fabric-community/spooky-time#69]
What kind of RPG mod would Spooky Time be if it didn't have fun loot chests?
The _Spooky Treasure Chest_ is a new block. When clicked, it displays a fun animation and then drops loot.

**Visuals:**
1/3 of a block big, centered in the middle bottom. I'm thinking it could have a BER and slowly float up and down.

**Spawning:**
The Spooky Treasure Chest spawns in dungeons & structures and under certain land formations (trees, rocks, brush). They can also be found in caves underground.

**Technical:**
When clicked, the chest is replaced by a Treasure Chest Entity at the same location (which is disguised by a burst of smoke). A spooky laugh sound is played to all nearby players. The entity slowly rotates up as the lid opens up. After floating ~2 blocks upwards, the chest faces whoever opened it, and then drops loot.

**Potential Drops:**
- Pumpkin pool
- Candy pool
- Block pool (soul sand, cobweb, mod blocks)
- Bones
- Spookium and other mod resources
- Mod tools (rare)
- Vanilla resources (diamonds, emeralds, gold)

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/66170393-b490e680-e609-11e9-87fc-50216630f2ec.png)
nice

**Comment by valoeghese** [comment]
Nice
