### ISSUE TITLE
Vampirism & Beheading

### ISSUE THREAD

**Issue by Draylar** [fabric-community/spooky-time#72]
Introducing 2 new enchantments: [Vampirism & Beheading](https://github.com/fabric-community/spooky-time/issues/2#issuecomment-537142074). 

**Vampirism:**
An enchant that steals life from the enemy. It is only applied when the enemy is hit by a full charge attack and works on any melee weapon. It doesn't work on undead mobs. Uncommon enchantment.

Vampirism has 3 levels, each of which scales the life-steal percentage:
- level 1 -> 5% heal
- level 2 -> 10% heal
- level 3 -> 15% heal

Vampires don't like fire; this enchantment is incompatible with Fire Aspect.

**Beheading:**
Wouldn't be a spooky mod if we didn't do something with skulls! Beheading increases the chance of a head drop from a killed entity. Rare enchantment.

Beheading has 5 levels, each of which increases the head drop chance:
- level 1 -> 5% chance
- level 2 -> 7% chance
- level 3 -> 10% chance
- level 4 -> 12% chance
- level 5 -> 15% chance

Beheading is incompatible with looting.

**Comment by vini2003** [comment]
Done in PR #89.
